### PR TITLE
chrono patch

### PR DESCRIPTION
**Pull request by k3yavi**
Adding time to logs, help taken from [here](https://rust-lang-nursery.github.io/rust-cookbook/logging.html).

### CODE REVIEW

**Comment by seanmonstar** [comment]
Cool! I'm generally fine with being able to add some timestamps. Keeping with the "pretty" vibe, it should probably be kept pleasing to look at. Do you have an example of what this outputs?

**Comment by k3yavi** [comment]
Currently it looks as follows
screen shot 2018-07-08 at 11 14 59 am

Although it can use some of your design skills ;) !

**Comment by k3yavi** [comment]
Any comment/update on this ?

**Comment by bemeurer** [comment]
I'd really like to have this!

**Comment by nvll** [comment]
I was looking into this myself today. Anything we can do to smooth this out and get it in?

**Comment by k3yavi** [comment]
for what it's worth, I am currently using it from [here](https://github.com/k3yavi/pretty-env-logger).

**Comment by seanmonstar** [comment]
Sorry for the delay, let's get this in!

**Pull request merged**
